spring:
  application:
    name: kitsu-api
    
kitsu-api:
  client:
    service-url: https://kitsu.io
    service-anime-endpoint: /api/edge/anime
    service-anime-filter: /api/edge/episodes
    service-manga-endpoint: /api/edge/manga
    service-manga-filter: /api/edge/chapters
    service-name: kitsu